### ISSUE TITLE
Add Dataset

### ISSUE THREAD

**Issue by DRedDevil04** [opencodeiiita/YADD#1]
**Fork and Add Datasets:** Fork the repository, clone it locally, create a new branch, add datasets in `/data/` following guidelines, and submit a pull request.

**Contribution Guidelines:** Refer to `/data/CONTRIBUTING.md` for detailed instructions on dataset format and ensure adherence to specified column structure.

**Comment by k7aditya** [comment]
claim

**Comment by lamel0rd** [comment]
This issue is only for first-come first-serve basis?

**Comment by DRedDevil04** [comment]
@akoolarni yes...but more instances of similar issues will be added soon

**Comment by aryan0931** [comment]
claim

**Comment by DRedDevil04** [comment]
@k7aditya Assigned

**Comment by Aryan4884** [comment]
claim

**Comment by vineeshmittal1** [comment]
claim

**Comment by Nandinig24** [comment]
claim

**Comment by DRedDevil04** [comment]
@k7aditya please provide an update on the Issue...ping me on Discord

**Comment by rnavaneeth992** [comment]
claim

**Comment by Rohit-110** [comment]
claim
