### ISSUE TITLE
Data Standardisation and Cleaning

### ISSUE THREAD

**Issue by DRedDevil04** [opencodeiiita/YADD#11]
#### Issue Description
📄 **Task:** Develop a Python notebook to facilitate the integration of three provided datasets. The goal is to standardize labels and features, ensuring consistency across all datasets. Additionally, implement data cleaning procedures to enhance data quality. Finally, store the processed data in variables X (features) and Y (labels), with labels being binary (0 or 1) to represent the presence or absence of a DDoS attack.

#### Implementation Steps
1. **Data Reading:**
   - Create functions to read data from the three datasets, considering their respective formats.

2. **Standardization:**
   - Standardize labels and features across datasets to ensure uniformity.
   - Align features to match their corresponding counterparts in other datasets.
   - Then **CONCATENATE** all three datasets

3. **Data Cleaning:**
   - Implement cleaning procedures to handle missing values, outliers, or any inconsistencies in the datasets.

4. **Label Standardization:**
   - Convert labels to binary values (0 or 1) based on the presence or absence of DDoS attacks.

5. **Variable Assignment:**
   - Store the standardized and cleaned data in variables, assigning features to variable X and labels to variable Y.

#### Additional Considerations
- **Documentation:**
  - Provide inline comments and documentation for each step to enhance code readability.
  
- **Testing:**
  - Include testing steps to ensure the notebook produces the expected results.

- **Guidelines:**
  - Adhere to the project's coding and documentation guidelines.

**Comment by rnavaneeth992** [comment]
claim

**Comment by kushal7201** [comment]
claim

**Comment by prakhar-py** [comment]
claim

**Comment by Rohit-110** [comment]
ckkaim

**Comment by GovindaRohith** [comment]
Claim

**Comment by QuantTitan** [comment]
claim

**Comment by Piyush-Raj-Tiwari** [comment]
Claim

**Comment by DRedDevil04** [comment]
@rnavaneeth992 Assigned

**Comment by DRedDevil04** [comment]
@rnavaneeth992 react 👍 to this comment to confirm

**Comment by DRedDevil04** [comment]
@rnavaneeth992 you have been unassigned as you already have more than 3 issues assigned to you

**Comment by DRedDevil04** [comment]
@kushal7201 Assigned...confirm by reacting👍
