### ISSUE TITLE
Add 3rd dataset 

### ISSUE THREAD

**Issue by DRedDevil04** [opencodeiiita/YADD#3]
**Fork and Add Datasets:** Fork the repository, clone it locally, create a new branch, add datasets in `/data/` following guidelines, and submit a pull request.

**Contribution Guidelines:** Refer to `/data/CONTRIBUTING.md` for detailed instructions on dataset format and ensure adherence to specified column structure.

**Comment by prakhar-py** [comment]
claim

**Comment by DRedDevil04** [comment]
@tonyStark-Jr Assigned

**Comment by Aryan4884** [comment]
claim

**Comment by ajay484** [comment]
claim i want to work on this issue

**Comment by Nandinig24** [comment]
claim
